### PR TITLE
Add ES2015/6

### PR DESCRIPTION
**Pull request by maheshsundaram**
Use as much ES6 as Node 5 allows

### CODE REVIEW

**Comment by maheshsundaram** [comment]
There are some significant changes here so open to discussing and also keeping this as a fork.

**Comment by hemanth** [comment]
Yeah it's good to have this, but there will be some versions of node we will be missing out, should we be worried about them?

**Comment by maheshsundaram** [comment]
Yes that's a good point that it will limit which versions you can use.. But most people are keen to upgrade, I think. It's up to you - happy to leave/close this.

**Comment by hemanth** [comment]
@jasonmendes Let us merge this, people who use `ramda` wouldn't be on older version ;)

Thanks!

**Pull request merged**
