### PR TITLE
New user greeting 

### PR DESCRIPTION
**Pull request by ythecombinator**
Hey, nothing too special 'bout this _PR_, it just adds a fancier user greeting.

The proposed new user greeting is based on _ramda + REPL_ logo I drew - which uses the `RBNo2.1a Book` font:

Logo

Then I made an _ASCII-alike_ version of the logo above:

``` sh
 λλλλλλλλ                                         
λλλλλλλλλλ                                        
λλ λλλλλλλλλλλ                                    
λλλλλλλλλλλλλλλ                                   
   λλλλλλλλλλλλ      λλλλ    λλλλλ   λλλλλ    λλ  
   λλλλ  λλλλλλ      λλ λλ   λλ      λλ λλ    λλ  
  λλλλ    λλλλλλ     λλλλλ   λλλλλ   λλλλλ    λλ  
 λλλλ      λλλλλ     λλ λλ   λλ      λλλλλ    λλ  
λλλλ        λλλλ     λλ λλ   λλλλλ   λλ       λλλλ
```

Here you can see a comparison:

**Before**:

Before

**After**:

After

> Some _design/code notes_:
> 1. I used only `λ` in the drawing to match the _funcional identity_ of the project.
> 2. I used the `magenta` color from [chalk](https://github.com/chalk/chalk#colors) to match _randa_'s visual identity.
> 3. I wouldn't attach the `greeting.js` file to the package - and then keep the greeting code in the `index.js` - but I thought it'd make more sense to keep the code **modular** and them just _require_ the `greeting.js` file in the `index.js`.

Hope you like it :smile: 

> BTW, pretty interesting project!

### CODE REVIEW

**Comment by hemanth** [comment]
Awesome stuff, thanks! @mabrasil

**Comment by ythecombinator** [comment]
thanx :smile_cat:

**Comment by hemanth** [comment]
@mabrasil Will redo the gif and release the new version.

**Comment by hemanth** [comment]
@mabrasil Does this look ok? (it doesn't look as good as...)

screen shot 2016-01-19 at 12 37 09 pm

**Comment by ythecombinator** [comment]
At the moment, I had only a _cmder_ example to attach in my _PR_ and, yeah, maybe in your terminal - _iTerm2_, right? - it looks a bit different. But it' almost the very same greeting :smile: 

Maybe you don't like the `cyan` shade from [Chalk](https://github.com/chalk/chalk) but it's the the one which most matches with [ramda](http://ramdajs.com/0.19.0/index.html)'s - which is something like [`#693476`](http://www.colorhexa.com/693476) - since Chalk is aware of working on all terminals and systems and doesn't support other colors than the base [eight ones](https://github.com/chalk/chalk#colors). For a more accurate shade, [ansi-256-colors](https://github.com/jbnicolai/ansi-256-colors) could be used, but it wouldn't be a good idea in terms of _compatibility cross terminals/systems_. 

Maybe you don't like the _`λ`-based_ drawing, but I think it good to keep the _funcional identity_ of the project. Also, a _multi-character-based_ one wouldn't be so cool, e.g.

```
 .ohddho.                                         
:Ny///yNN/                                        
yd .+shNNNhy+`                                    
.yo/+-hNmNNNNm.                                   
   ``dN+.mNyNNo      +++/    .+//.   `o/+:    :.  
   .dN/  .mNNNd      d` h.   -y      `d `d    s:  
  -mN:    -mNNN-     d++d`   -d//`   `m`.d    s:  
 -mm-      -NNyo     d` h.   -y      `m::.    s:  
-dd-        :dhs     h` s.   -h//.   `h       oo/:
```

Don't you think so @hemanth?

**Comment by hemanth** [comment]
λ-based drawing looks fine.

I used solarized theme for terminal.

I am ok with the color, but the `R` and `P` doesn't look evident.

**Comment by ythecombinator** [comment]
Hey, I thought about an approach based on a `Aaargh`-alike font to make both `R` and `P` more clear:

```
 λλλλλλλλ                                                             
λλλλλλλλλλ                                                            
λλλλλλλλλλλλλλ                                                        
  λλλλλλλλλλλλλ     λλλλλλλ        λλλλλλλ       λλλλλλλ        λλ    
   λλλλ  λλλλλλλ    λλ   λλ        λλ            λλ    λ        λλ    
  λλλλ    λλλλλλ    λλλλλλλ        λλλλλλλ       λλλλλλλ        λλ    
 λλλλ      λλλλλ    λλ  λλλ        λλ            λλ             λλ    
λλλλ        λλλλ    λλ   λλλ       λλλλλλλ       λλ             λλλλλλ
```

and it goes like this in the terminal:

new one

What do you think @hemanth?

**Comment by hemanth** [comment]
Sorry, if I am too specific here, should there be space between `λ` and `R`?

**Comment by ythecombinator** [comment]
I don't know if I got what you mean @hemanth, but you say something like this:

```
 λλλλλλλλ                                                             
λλλλλλλλλλ                                                            
λλλλλλλλλλλλλλ                                                        
  λλλλλλλλλλλλλ               λλλλλλλ        λλλλλλλ       λλλλλλλ        λλ    
   λλλλ  λλλλλλλ              λλ   λλ        λλ            λλ    λ        λλ    
  λλλλ    λλλλλλ              λλλλλλλ        λλλλλλλ       λλλλλλλ        λλ    
 λλλλ      λλλλλ              λλ  λλλ        λλ            λλ             λλ    
λλλλ        λλλλ              λλ   λλλ       λλλλλλλ       λλ             λλλλλλ
```

where _ramda_'s logo and the `R` from _REPL_ are more spaced?

**Comment by hemanth** [comment]
What I meant was: The spaces between R E P L and the space between Ramda Logo and R must be the same.

**Comment by ythecombinator** [comment]
Oh, sorry, now I see.

How about this:

```
 λλλλλλλλ                                                             
λλλλλλλλλλ                                                            
λλλλλλλλλλλλλλ                                                        
  λλλλλλλλλλλλλ         λλλλλλλ         λλλλλλλ        λλλλλλλ        λλ    
   λλλλ  λλλλλλλ        λλ   λλ         λλ             λλ    λ        λλ    
  λλλλ    λλλλλλ        λλλλλλλ         λλλλλλλ        λλλλλλλ        λλ    
 λλλλ      λλλλλ        λλ  λλλ         λλ             λλ             λλ    
λλλλ        λλλλ        λλ   λλλ        λλλλλλλ        λλ             λλλλλλ
```

Exactly `8` whitespaces between each right edge of a character and the following left edge.

What do you think?

**Comment by ythecombinator** [comment]
Any feedback @hemanth?

**Comment by hemanth** [comment]
Sorry, I had missed this, looks great now :+1:

**Comment by ythecombinator** [comment]
I'll updte the code and then send a new _PR_ in a few minutes :smile:

**Comment by ythecombinator** [comment]
Done here #9

**Pull request merged**
